# src/main/resources/message/salable_component/product_msg.properties

product_alreadyExists.name.brand.model = Falha de duplicação ao tentar salvar novo `Product`: [name: `{0}`; brand: `{1}`; model: `{2}`].