# src/main/resources/message/salable_component/salable_component_msg.properties

concurrent_save_process.entityName = Falha interna ao tentar salvar nova entidade: `{0}`. Tente novamemte ou acione o suporte.
not_found.entityName.id = Não foi possível encontrar `{0}` para o id: `{1}`.