# src/main/resources/message/salable_component/conventional/service_msg.properties

service_alreadyExists.name.category = Falha de duplicidade ao tentar salvar novo `Service`: [name: `{0}`; category: `{1}`].